version: '2.4'
services:
  config:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
    image: aydarik/ancestry-config
    restart: on-failure

  registry:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
    image: aydarik/ancestry-registry
    restart: on-failure
    depends_on:
      config:
        condition: service_healthy
    ports:
      - 8761:3000

  gateway:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
    image: aydarik/ancestry-gateway
    restart: on-failure
    depends_on:
      config:
        condition: service_healthy
      registry:
        condition: service_started
    ports:
      - 80:4000

  account-service:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      ACCOUNT_SERVICE_PASSWORD: $ACCOUNT_SERVICE_PASSWORD
      POSTGRESQL_PASSWORD: $POSTGRESQL_PASSWORD
    image: aydarik/ancestry-account-service
    restart: on-failure
    depends_on:
      config:
        condition: service_healthy
      registry:
        condition: service_started
      account-postgresql:
        condition: service_started

  account-postgresql:
    environment:
      POSTGRES_DB: ancestry
      POSTGRES_USER: user
      POSTGRES_PASSWORD: $POSTGRESQL_PASSWORD
    image: postgres:11
    restart: on-failure
#    volumes:
#      - R:\account-service\database:/var/lib/postgresql/data:rw

#  monitoring:
#    environment:
#      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
#    image: aydarik/ancestry-monitoring
#    restart: on-failure
#    depends_on:
#      config:
#        condition: service_healthy
#    ports:
#      - 9000:8080
#      - 8989:8989
