version: '2.4'
services:
  config:
    build: config
    ports:
      - 8000:8000

  registry:
    build: registry

  gateway:
    build: gateway

  account-service:
    build: account-service
    ports:
      - 6000:6000

  account-postgresql:
    ports:
      - 26000:5432

#  monitoring:
#    build: monitoring
