logging:
  level:
    org.springframework.security: DEBUG

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
#      defaultZone: http://registry:3000/eureka/
      defaultZone: http://localhost:3000/eureka/

security:
  oauth2:
    resource:
#      user-info-uri: http://account-service:5000/users/current
      user-info-uri: http://localhost:5000/users/current
