spring:
  data:
    postgresql:
      host: auth-postgresql
      username: user
      password: ${POSTGRESQL_PASSWORD}
      database: ancestry
      port: 5432

server:
  context-path: /uaa
  port: 5000
