zuul:
  ignoredServices: '*'
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000

  routes:
    account-service:
        path: /users/**
        serviceId: account-service
        stripPrefix: true
        sensitiveHeaders:

server:
  port: 4000
